import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import stays the same
import "./globals.css";
import Navbar from "./component/Navbar";
import { NavbarDefaults } from "@/lib/navbarData";

// Rename the variable to avoid conflicts
const interFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} font-sans`}>
        <Navbar {...NavbarDefaults} />
        {children}
      </body>
    </html>
  );
}
